services:
  api-gateway:
    build: .
    container_name: api-gateway
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - "80"
    networks:
      centinela-net:
        aliases:
          - api-gateway

networks:
  centinela-net:
    external: true
